// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzylostlaaxjvnijypcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56eWxvc3RsYWF4anZuaWp5cGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDM1MjYsImV4cCI6MjA2MzgxOTUyNn0.cY08Ri6UUqhWaUGhFLaB0CEtEG1ND3Rw6i-KEnvJtAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);